"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { motion, useMotionValue, useSpring, useScroll, useTransform } from "framer-motion";
import { getSupabase } from "../lib/supabase-browser";
import { ArrowUpRight, Award, BookOpen, BriefcaseBusiness, Code2, Download, ExternalLink, GitBranch, GraduationCap, Mail, MapPin, Menu, Network, Radio, School, Sparkles, Terminal, Trophy, Users, X } from "lucide-react";

const navItems = ["About", "Projects", "Experience", "Education", "Contact"];
const projects = [
  { number: "01", title: "Agentic AI Research Workspace", description: "A focused research environment that orchestrates context, automation, and useful decisions through agentic workflows.", tags: ["Python", "Agentic AI", "Automation"], tone: "violet", icon: Network },
  { number: "02", title: "Database Management System", description: "A practical relational system with clear data models, dependable queries, and the fundamentals that make software trustworthy.", tags: ["C++", "SQL", "Systems"], tone: "lime", icon: BriefcaseBusiness },
  { number: "03", title: "CPU Scheduling Simulator", description: "An interactive simulator that makes operating system scheduling concepts tangible through comparative visual feedback.", tags: ["C++", "Algorithms", "Visualization"], tone: "blue", icon: Radio },
  { number: "04", title: "Full Stack Web Platform", description: "A responsive application with authentication, CRUD workflows, REST APIs, and a relational data layer for real users.", tags: ["JavaScript", "REST APIs", "PostgreSQL"], tone: "orange", icon: Code2 },
];
const experience = [
  { period: "2025 to 2026", role: "Web Development Intern", company: "HUM Network Ltd", detail: "Built responsive full stack interfaces, CRUD workflows, relational schemas, session authentication, and REST APIs." },
  { period: "2025", role: "Undergraduate Teaching Assistant", company: "FAST NUCES", detail: "Supported teaching and student learning across Multivariate Calculus and Ideology and Constitution of Pakistan." },
];
const volunteering = [
  { period: "Oct 2025 to Feb 2026", role: "Co Head, Computer Science Competitions", company: "PROCOM", detail: "Led competition delivery, problem design, technical logistics, and live operations for a major university technology event." },
  { period: "Apr 2025", role: "Assessment Management", company: "Developers Day, ACM NUCES", detail: "Managed assessments and general competitions while keeping technical operations calm and dependable." },
  { period: "Mar 2025", role: "Outreach Volunteer", company: "Alkhidmat Karachi", detail: "Supported public engagement and outreach activities with a focus on community participation." },
  { period: "2023", role: "Community Service Volunteer", company: "Dar ul Sukun", detail: "Coordinated class visits and supported child welfare programs through direct community service." },
];
const skills = ["C and C++", "Python", "Java", "JavaScript", "SQL and Databases", "REST APIs", "Git and GitHub", "Systems Programming", "Automation", "Agentic AI"];

function ParticleField() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const pointerX = useMotionValue(0.5);
  const pointerY = useMotionValue(0.35);
  const smoothX = useSpring(pointerX, { stiffness: 45, damping: 22 });
  const smoothY = useSpring(pointerY, { stiffness: 45, damping: 22 });
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let frame = 0;
    const particles = Array.from({ length: 115 }, (_, index) => ({ x: (index * 73) % 1000, y: (index * 137) % 800, r: 1 + (index % 3) * 0.6, speed: 0.15 + (index % 5) * 0.04 }));
    const resize = () => { canvas.width = window.innerWidth * devicePixelRatio; canvas.height = window.innerHeight * 1.5 * devicePixelRatio; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); };
    const draw = () => { const width = window.innerWidth; const height = window.innerHeight * 1.5; ctx.clearRect(0, 0, width, height); const px = smoothX.get() * width; const py = smoothY.get() * height; particles.forEach((particle, index) => { particle.y -= particle.speed; if (particle.y < -10) particle.y = height + 10; const x = (particle.x / 1000) * width + Math.sin(frame * 0.006 + index) * 14; const y = particle.y; const distance = Math.hypot(x - px, y - py); const glow = Math.max(0, 1 - distance / 420); ctx.beginPath(); ctx.fillStyle = `rgba(218, 255, 117, ${0.14 + glow * 0.55})`; ctx.arc(x, y, particle.r + glow * 2, 0, Math.PI * 2); ctx.fill(); }); frame += 1; requestAnimationFrame(draw); };
    resize(); window.addEventListener("resize", resize); draw(); return () => window.removeEventListener("resize", resize);
  }, [smoothX, smoothY]);
  return <motion.div className="particle-field" onPointerMove={(event) => { pointerX.set(event.clientX / window.innerWidth); pointerY.set(event.clientY / window.innerHeight); }}><canvas ref={canvasRef} /><div className="motion-image" /></motion.div>;
}

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.16 }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>; }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false); const [visits, setVisits] = useState<number | null>(null); const { scrollYProgress } = useScroll(); const progress = useTransform(scrollYProgress, [0, 1], ["0%", "100%"]);
  useEffect(() => { const counted = sessionStorage.getItem("za-visit-counted"); const loadVisits = async () => { const supabase = getSupabase(); if (!supabase) return; if (!counted) { const { data } = await supabase.rpc("increment_site_visit", { stat_id: "portfolio" }); if (typeof data === "number") setVisits(data); sessionStorage.setItem("za-visit-counted", "true"); } else { const { data } = await supabase.from("site_stats").select("visits").eq("id", "portfolio").maybeSingle(); if (typeof data?.visits === "number") setVisits(data.visits); } }; loadVisits().catch(() => setVisits(null)); }, []);
  const scrollTo = (id: string) => { document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  return <main className="site-shell"><motion.div className="scroll-progress" style={{ width: progress }} /><ParticleField />
    <header className="site-header glass-panel"><a className="wordmark" href="#about" aria-label="Zubair Ahmed home"><span>ZA</span><b>creative systems</b></a><nav className={`main-nav ${menuOpen ? "is-open" : ""}`} aria-label="Primary navigation">{navItems.map((item) => <button key={item} onClick={() => scrollTo(item)}>{item}</button>)}<a href="/ZA_Resume.pdf" download="Zubair Ahmed Resume.pdf" className="nav-resume">Resume <Download size={14} /></a></nav><button className="menu-toggle" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="about" className="hero section-wrap"><Reveal className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for meaningful work</p><h1>Ideas into<br /><em>useful systems.</em></h1><p className="hero-intro">I am Zubair Ahmed, a Computer Science undergraduate and software developer focused on systems, applied AI, and the details that make technology feel effortless.</p><div className="hero-actions"><button className="button button-primary" onClick={() => scrollTo("projects")}>Explore projects <ArrowUpRight size={17} /></button><a className="button button-quiet" href="mailto:zahmad2812@gmail.com">Let us talk <Mail size={16} /></a></div><div className="hero-meta"><span><MapPin size={15} /> Karachi, Pakistan</span><span><Terminal size={15} /> CS at FAST NUCES</span></div></Reveal><Reveal className="hero-visual"><div className="portrait-frame"><Image src="/procom-event.jpg" alt="Zubair Ahmed at a technology event" fill priority sizes="(max-width: 768px) 88vw, 430px" /></div><div className="visual-caption"><span>01 / 04</span><span>Software, AI, systems</span></div></Reveal></section>
    <div className="ticker" aria-label="Focus areas"><div className="ticker-track"><span>Software development</span><span>Applied artificial intelligence</span><span>Technical leadership</span><span>Systems thinking</span><span>Software development</span><span>Applied artificial intelligence</span></div></div>
    <Reveal><section id="projects" className="section-wrap content-section"><div className="section-heading"><p className="eyebrow">Selected projects</p><h2>Built with curiosity<br />and purpose.</h2><p className="section-lede">Four projects that represent how I think: start with the problem, understand the system, then make the experience clear.</p></div><div className="project-grid">{projects.map((project) => { const Icon = project.icon; return <motion.article whileHover={{ y: -10, rotate: project.number === "02" ? -1 : 1 }} transition={{ type: "spring", stiffness: 260, damping: 18 }} className={`project-card ${project.tone}`} key={project.number}><div className="project-number">{project.number}</div><div className="project-art"><Icon size={38} strokeWidth={1.4} /></div><div><h3>{project.title}</h3><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><ExternalLink className="card-arrow" size={18} /></motion.article>; })}</div></section></Reveal>
    <Reveal><section id="experience" className="section-wrap split-section"><div className="section-heading sticky-heading"><p className="eyebrow">Professional experience</p><h2>Learn by<br /><em>doing.</em></h2><p className="section-lede">Shipping software taught me to value ownership, clear communication, and outcomes that last beyond launch.</p></div><div className="timeline">{experience.map((item) => <article className="timeline-item" key={item.role}><span className="timeline-period">{item.period}</span><div><h3>{item.role}</h3><p className="company">{item.company}</p><p>{item.detail}</p></div></article>)}</div></section></Reveal>
    <Reveal><section id="volunteering" className="section-wrap split-section volunteer-section"><div className="section-heading sticky-heading"><p className="eyebrow">Volunteer work</p><h2>People make<br /><em>the work.</em></h2><p className="section-lede">Leadership and community work shaped how I collaborate, organize, and help a team move with confidence.</p></div><div className="timeline">{volunteering.map((item) => <article className="timeline-item" key={item.role}><span className="timeline-period">{item.period}</span><div><h3>{item.role}</h3><p className="company">{item.company}</p><p>{item.detail}</p></div></article>)}</div></section></Reveal>
    <Reveal><section id="education" className="section-wrap content-section"><div className="section-heading"><p className="eyebrow">Education and foundations</p><h2>Curiosity,<br /><em>structured.</em></h2></div><div className="education-grid"><article className="education-card featured"><GraduationCap size={24} /><p className="card-kicker">2023 to 2027</p><h3>BS Computer Science</h3><p>FAST NUCES, Karachi</p><span>Agentic AI, Computer Architecture, Operations Research, Software Project Management</span></article><article className="education-card"><School size={22} /><p className="card-kicker">2022 to 2023</p><h3>A Levels</h3><p>Cedar College, Karachi</p><span>Computer Science, Mathematics, Physics, Chemistry</span></article><article className="education-card"><BookOpen size={22} /><p className="card-kicker">2019 to 2020</p><h3>O Levels</h3><p>Montessori Complex Cambridge School</p><span>Mathematics, Additional Mathematics, Computer Science, Physics, Chemistry, English, Islamiat, Urdu, Pakistan Studies</span></article></div></section></Reveal>
    <Reveal><section id="skills" className="section-wrap skills-section"><div className="skills-intro"><p className="eyebrow">Toolkit</p><h2>Enough tools<br />to make ideas real.</h2></div><div className="skills-content"><p>I enjoy moving between abstraction levels, from architecture and databases to the interface a person actually touches.</p><div className="skill-cloud">{skills.map((skill) => <span key={skill}><Code2 size={14} />{skill}</span>)}</div></div></section></Reveal>
    <Reveal><section className="section-wrap recognition"><div><p className="eyebrow">Recognition</p><h2>Earned in<br /><em>the room.</em></h2></div><div className="awards"><div><Trophy /><p><strong>Star Performer Award</strong><br />PROCOM 25, Management and Leadership</p></div><div><Award /><p><strong>Star Performer Award</strong><br />Developers Day 25, Assessment and General Management</p></div><div><Sparkles /><p><strong>Achievement Award</strong><br />Integration Bee 2023, Mathematics Competition</p></div></div></section></Reveal>
    <section id="contact" className="contact-section"><div className="section-wrap contact-inner"><div><p className="eyebrow">Have a good problem?</p><h2>Let us make<br /><em>something useful.</em></h2></div><a className="contact-email" href="mailto:zahmad2812@gmail.com">zahmad2812@gmail.com <ArrowUpRight /></a></div></section>
    <footer className="footer section-wrap"><div className="footer-brand"><span>ZA</span><p>Software developer building at the intersection of systems, AI, and people.</p></div><div className="footer-links"><a href="https://github.com/zahmed02" target="_blank" rel="noreferrer"><GitBranch size={17} /> GitHub</a><a href="https://linkedin.com/in/zubair-ahmed-448041344" target="_blank" rel="noreferrer"><ArrowUpRight size={17} /> LinkedIn</a><a href="mailto:zahmad2812@gmail.com"><Mail size={17} /> Email</a></div><div className="footer-bottom"><span>Copyright {new Date().getFullYear()} Zubair Ahmed</span><span className="visitor-count"><Users size={14} /> {visits === null ? "Visitors counted privately" : `${visits.toLocaleString()} visits`}</span><span>Designed and built with care</span></div></footer>
  </main>;
}
